export function isArabicLanguage(language: string) {
  return language.startsWith("ar");
}

export function pickText(isArabic: boolean, english: string, arabic: string) {
  return isArabic ? arabic : english;
}

const translations: Record<string, string> = {
  "Organizing company intake": "إدخال الشركة المنظمة",
  "Enter activity requirements before operations are opened":
    "إدخال متطلبات الفعالية قبل فتح العمليات",
  "The organizing company enters the activity, guests, VIP rules, tickets, hotels, and cars. Midyaf AI prepares the logistics plan, then vendor quotations and contracts are managed by the logistics team.":
    "تدخل الشركة المنظمة بيانات الفعالية والضيوف وقواعد كبار الشخصيات والتذاكر والفنادق والسيارات. ثم يحضر ذكاء مضياف خطة التشغيل، وبعدها يدير فريق اللوجستيات عروض الموردين والعقود.",
  "Activity input": "بيانات الفعالية",
  "Activity name": "اسم الفعالية",
  "Activity place": "مكان الفعالية",
  "Total visitors": "إجمالي الزوار",
  "VIP visitors": "زوار كبار الشخصيات",
  Transportation: "النقل",
  Tickets: "التذاكر",
  Hotels: "الفنادق",
  Cars: "السيارات",
  "VIP dedicated cars": "سيارات مخصصة لكبار الشخصيات",
  "One car per VIP for full stay": "سيارة واحدة لكل ضيف VIP طوال فترة الإقامة",
  "Normal shuttle groups": "مجموعات النقل الجماعي",
  "3-4 guests per group": "٣ إلى ٤ ضيوف لكل مجموعة",
  "Planning status": "حالة التخطيط",
  "AI ready": "الخطة الذكية جاهزة",
  "Confirm before vendor RFQs": "تعتمد قبل طلب عروض الموردين",
  "Analyze with AI and prepare logistics plan":
    "تحليل بالذكاء الاصطناعي وتجهيز خطة اللوجستيات",
  "Save activity intake": "حفظ بيانات الفعالية",
  Saving: "جاري الحفظ",
  Analyzing: "جاري التحليل",
  "AI plan output": "مخرجات الخطة الذكية",
  AI: "ذكاء اصطناعي",
  Saud: "سعود",
  Noura: "نورة",
  "Ops Manager": "مدير العمليات",
  "Supply Chain AI": "ذكاء سلسلة الإمداد",
  "Plan confirmed": "الخطة معتمدة",
  "Awaiting confirmation": "بانتظار الاعتماد",
  "GPT-4o planning": "تخطيط GPT-4o",
  "VIP cars": "سيارات VIP",
  "Shuttle vehicles": "مركبات النقل الجماعي",
  "Hotel rooms": "غرف الفندق",
  "Guest App": "تطبيق الضيف",
  "hospitality journey": "رحلة الضيافة",
  "Visa, tickets, promotional videos, arrival tracking, event transportation, personal requests, complaints, and departure timing.":
    "التأشيرة والتذاكر والفيديوهات التعريفية وتتبع الوصول ونقل الفعالية والطلبات الخاصة والشكاوى وتوقيت المغادرة.",
  "1. Arrival": "١. الوصول",
  "2. Event transport": "٢. نقل الفعالية",
  "3. Departure": "٣. المغادرة",
  Gate: "البوابة",
  pickup: "موعد التحرك",
  "Hotel to venue and return": "من الفندق إلى موقع الفعالية والعودة",
  "Documents and hospitality media": "المستندات ومواد الضيافة",
  Visa: "التأشيرة",
  "Visa document sent to guest app.": "تم إرسال التأشيرة إلى تطبيق الضيف.",
  "Event ticket and seating class sent.": "تم إرسال تذكرة الفعالية وفئة المقعد.",
  "Country and hospitality preview video": "فيديو تعريفي عن المملكة وتجربة الضيافة",
  "Uploaded hospitality video": "فيديو ضيافة مرفوع",
  "Open file": "فتح الملف",
  "Delivery notifications": "إشعارات الإرسال",
  "Notification delivery log": "سجل إرسال الإشعارات",
  "No delivery notifications yet": "لا توجد إشعارات إرسال بعد",
  Recipient: "المستلم",
  "Arrival status updates": "تحديثات حالة الوصول",
  "Car arrives in": "السيارة تصل خلال",
  minutes: "دقائق",
  "Guest should be notified to wait outside before the captain arrives.":
    "يجب تنبيه الضيف للانتظار في الخارج قبل وصول الكابتن.",
  "Captain and car details": "بيانات الكابتن والسيارة",
  "VIP dedicated car": "سيارة مخصصة لكبار الشخصيات",
  "Grouped shuttle": "نقل جماعي",
  "Special requests, notes, complaints": "الطلبات الخاصة والملاحظات والشكاوى",
  "Add request, note, or complaint": "أضف طلباً أو ملاحظة أو شكوى",
  Send: "إرسال",
  "Departure confirmation": "تأكيد المغادرة",
  Flight: "الرحلة",
  "Leave hotel": "مغادرة الفندق",
  "Midyaf transport": "النقل مع مضياف",
  Yes: "نعم",
  No: "لا",
  "Timing confirmed": "تأكيد التوقيت",
  Confirmed: "مؤكد",
  Pending: "بانتظار التأكيد",
  "Captains App": "تطبيق الكباتن",
  "Shifts, tasks, car information, visit count, captain type, active status, overtime availability, and task feedback.":
    "الورديات والمهام وبيانات السيارة وعدد الرحلات ونوع الكابتن وحالة النشاط وإمكانية العمل الإضافي وتقييم المهمة.",
  "Shifts, tasks, car information, visit count, active status, overtime availability, and task feedback.":
    "الورديات والمهام وبيانات السيارة وعدد الرحلات وحالة النشاط وإمكانية العمل الإضافي وتقييم المهمة.",
  "Captain type": "نوع الكابتن",
  Active: "نشط",
  Inactive: "غير نشط",
  Shift: "الوردية",
  "Overtime available": "متاح للعمل الإضافي",
  "No overtime": "لا يوجد عمل إضافي",
  Visits: "الرحلات",
  Today: "اليوم",
  Earnings: "الأرباح",
  "Shift estimate": "تقدير الوردية",
  Car: "السيارة",
  "Task routes and feedback": "مسارات المهام والتقييم",
  "Captain media": "وسائط الكابتن",
  "No uploaded driver photo yet": "لا توجد صورة مرفوعة للكابتن بعد",
  "Guest photo ready": "صورة الضيف جاهزة",
  "Guest photo not uploaded yet": "لم يتم رفع صورة الضيف بعد",
  "Share location": "مشاركة الموقع",
  to: "إلى",
  Deadline: "الموعد النهائي",
  Complete: "إنهاء",
  "Add task feedback or system request": "أضف تقييم المهمة أو طلباً للنظام",
  Submit: "إرسال",
  "Coordinators App": "تطبيق المنسقين",
  "Guest requests and supervisor car allocation":
    "طلبات الضيوف وتوزيع السيارات على المشرفين",
  "Coordinators see who is coming from the airport, hotel, or venue, process guest car requests, escalate to supervisors, and submit feedback to the logistics manager.":
    "يرى المنسقون حركة الضيوف من المطار أو الفندق أو موقع الفعالية، ويعالجون طلبات السيارات، ويرفعونها إلى المشرفين، ويرسلون الملاحظات إلى مدير اللوجستيات.",
  "Who is moving now?": "من يتحرك الآن؟",
  "Guest group": "مجموعة ضيوف",
  "Requests to supervisors": "الطلبات المرسلة للمشرفين",
  "Coordinator feedback": "ملاحظات المنسق",
  "New supervisor request": "طلب جديد للمشرف",
  "Guest name": "اسم الضيف",
  Priority: "الأولوية",
  "Request summary": "ملخص الطلب",
  Route: "المسار",
  Supervisor: "المشرف",
  "Submit request": "إرسال الطلب",
  "Mark assigned": "تعيين الطلب",
  "Close request": "إغلاق الطلب",
  "Airport team needs updated guest photos before passport control.":
    "يحتاج فريق المطار إلى صور الضيوف المحدثة قبل نقطة الجوازات.",
  "VIP personal trip request sent to North Zone Supervisor.":
    "تم إرسال طلب الرحلة الخاصة للـ VIP إلى مشرف المنطقة الشمالية.",
  "Normal shuttle group 4 has one extra passenger.":
    "مجموعة النقل الجماعي رقم ٤ لديها راكب إضافي.",
  "Logistics Dashboard": "لوحة المنظم",
  "Logistics manager command dashboard": "لوحة تحكم مدير اللوجستيات",
  "The logistics manager owns the full event: tasks, managers, supervisors, captains, vendor contracts, deadlines, progress tracking, access distribution, and confirmed reports.":
    "مدير اللوجستيات يدير الفعالية بالكامل: المهام والمديرين والمشرفين والكباتن وعقود الموردين والمواعيد النهائية وتتبع الإنجاز وتوزيع الصلاحيات والتقارير المعتمدة.",
  Visitors: "الزوار",
  "Open tasks": "المهام المفتوحة",
  "Owners and deadlines assigned": "تم تحديد الملاك والمواعيد النهائية",
  Contracts: "العقود",
  "Signed or active": "موقعة أو نشطة",
  Commission: "العمولة",
  "From approved quotations": "من العروض المعتمدة",
  Reports: "التقارير",
  "Manager confirmed": "معتمدة من المدير",
  "Task ownership and deadlines": "ملاك المهام والمواعيد النهائية",
  Owner: "المالك",
  "Managers and supervisors": "المديرون والمشرفون",
  "Operations setup": "إعدادات التشغيل",
  "Operations records are saved directly to PostgreSQL and are available to role portals after refresh.":
    "يتم حفظ سجلات التشغيل مباشرة في PostgreSQL وتظهر في بوابات الأدوار بعد التحديث.",
  "Bulk guest import": "استيراد الضيوف دفعة واحدة",
  "Paste a CSV guest list or load a CSV file. Midyaf creates guest accounts, journeys, QR invites, VIP cars, and normal shuttle groups.":
    "الصق قائمة ضيوف بصيغة CSV أو حمّل ملف CSV. ينشئ مضياف حسابات الضيوف، الرحلات، دعوات QR، سيارات VIP، ومجموعات النقل الجماعي للضيوف العاديين.",
  "Load CSV file": "تحميل ملف CSV",
  "Generate arrival transport tasks": "إنشاء مهام نقل الوصول",
  "Normal guests per shuttle": "عدد الضيوف العاديين لكل نقل جماعي",
  Importing: "جاري الاستيراد",
  "Import guests and generate tasks": "استيراد الضيوف وإنشاء المهام",
  "Use sample CSV": "استخدام نموذج CSV",
  "CSV must include headers and at least one guest row":
    "يجب أن يحتوي ملف CSV على عناوين وصف ضيف واحد على الأقل",
  "name, email, and phone are required":
    "الاسم والبريد الإلكتروني ورقم الجوال مطلوبة",
  "Add guest": "إضافة ضيف",
  "Email": "البريد الإلكتروني",
  "Phone": "رقم الجوال",
  "Name": "الاسم",
  "Guest tier": "فئة الضيف",
  "VIP guest": "ضيف VIP",
  "Temporary password": "كلمة مرور مؤقتة",
  "Create guest invite": "إنشاء دعوة الضيف",
  "Add captain": "إضافة كابتن",
  "Captain name": "اسم الكابتن",
  "License number": "رقم الرخصة",
  "Saudi National ID/Iqama": "رقم الهوية أو الإقامة",
  "Shift start": "بداية الوردية",
  "Shift end": "نهاية الوردية",
  "Current latitude": "خط العرض الحالي",
  "Current longitude": "خط الطول الحالي",
  "Create captain": "إنشاء كابتن",
  "Add supplier": "إضافة مورد",
  "Supplier name": "اسم المورد",
  Category: "التصنيف",
  Rating: "التقييم",
  "Verified supplier": "مورد موثق",
  "CR number": "رقم السجل التجاري",
  "Commission percent": "نسبة العمولة",
  "Service name": "اسم الخدمة",
  "Service price": "سعر الخدمة",
  "Service unit": "وحدة الخدمة",
  "Create supplier": "إنشاء مورد",
  "Add manager or coordinator": "إضافة مدير أو منسق",
  Role: "الدور",
  "Create user": "إنشاء مستخدم",
  "Create operational task": "إنشاء مهمة تشغيلية",
  "Auto assign nearest available captain": "سيتم تعيين أقرب كابتن متاح تلقائياً عند ترك خانة الكابتن فارغة",
  "Task type": "نوع المهمة",
  "Assigned captain": "الكابتن المعيّن",
  "Related guest": "الضيف المرتبط",
  "No assigned captain": "بدون كابتن محدد",
  "No related guest": "بدون ضيف مرتبط",
  "Pickup location": "موقع الانطلاق",
  "Dropoff location": "موقع الوصول",
  "Pickup latitude": "خط عرض الانطلاق",
  "Pickup longitude": "خط طول الانطلاق",
  "Dropoff latitude": "خط عرض الوصول",
  "Dropoff longitude": "خط طول الوصول",
  "Scheduled time": "وقت الجدولة",
  "Task owner": "مالك المهمة",
  "Create task": "إنشاء مهمة",
  "Task assignment board": "لوحة تعيين المهام",
  "Assigned tasks": "المهام المعينة",
  "Delayed tasks": "المهام المتأخرة",
  "No tasks in this column": "لا توجد مهام في هذا العمود",
  "Mark accepted": "تأكيد القبول",
  "Mark en route": "تحديد في الطريق",
  "Mark arrived": "تحديد الوصول",
  "Mark picked up": "تحديد الاستلام",
  "Mark completed": "إنهاء المهمة",
  "Mark delayed": "تحديد متأخرة",
  "Cancel task": "إلغاء المهمة",
  "Mark pending": "إعادة إلى قيد الانتظار",
  "Guest document dispatch": "إرسال مستندات الضيوف",
  "Upload visa": "رفع التأشيرة",
  "Upload ticket": "رفع التذكرة",
  "Upload guest photo": "رفع صورة الضيف",
  "Upload promo video": "رفع فيديو تعريفي",
  "Upload driver photo": "رفع صورة الكابتن",
  "No files uploaded yet": "لا توجد ملفات مرفوعة بعد",
  Uploading: "جاري الرفع",
  "Captains and priorities": "الكباتن والأولويات",
  "Driver status": "حالة السائق",
  Zone: "المنطقة",
  "Procurement Manager": "مدير المشتريات",
  "Vendor quotation and contracts": "عروض الموردين والعقود",
  "Airport Supervisor": "مشرف المطار",
  "Arrival gates and captain handoff": "بوابات الوصول وتسليم الضيف للكابتن",
  "North Zone Supervisor": "مشرف المنطقة الشمالية",
  "VIP trips and personal requests": "رحلات VIP والطلبات الخاصة",
  "Departure Supervisor": "مشرف المغادرة",
  "Flight confirmation and pickup timing": "تأكيد الرحلات وتوقيت التحرك",
  "Confirmed report package": "حزمة التقرير المعتمد",
  "Confirm report": "اعتماد التقرير",
  "PDF report can be sent only after logistics manager confirmation.":
    "لا يمكن إرسال تقرير PDF إلا بعد اعتماد مدير اللوجستيات.",
  "Company Dashboard": "لوحة الشركة المنظمة",
  "Organizing company visibility and approved updates":
    "متابعة الشركة المنظمة والتحديثات المعتمدة",
  "The organizing company can see logistics reports after manager confirmation, update activity data, and submit new tasks to the logistics manager for processing.":
    "يمكن للشركة المنظمة مشاهدة تقارير اللوجستيات بعد اعتماد المدير، وتحديث بيانات الفعالية، وإرسال مهام جديدة إلى مدير اللوجستيات للمعالجة.",
  "Activity summary": "ملخص الفعالية",
  Activity: "الفعالية",
  Place: "المكان",
  Status: "الحالة",
  "Confirmed reports": "التقارير المعتمدة",
  Updated: "آخر تحديث",
  "Download PDF report": "تحميل تقرير PDF",
  "Submit new data to logistics manager": "إرسال بيانات جديدة إلى مدير اللوجستيات",
  "Send update": "إرسال التحديث",
  "Updates become tasks for the logistics manager, who confirms scope, assigns managers or supervisors, then sends back approved reporting.":
    "تتحول التحديثات إلى مهام لدى مدير اللوجستيات، ثم يعتمد النطاق ويعين المديرين أو المشرفين ويرسل التقارير المعتمدة.",
  "Vendor quotations, contracts, and commissions":
    "عروض الموردين والعقود والعمولات",
  "Quotes received": "العروض المستلمة",
  "Midyaf commission": "عمولة مضياف",
  "Approve quote": "اعتماد العرض",
  "Approve contract": "اعتماد العقد",
  Score: "التقييم",
  "AI plan phases": "مراحل الخطة الذكية",
  "Confirm AI plan": "اعتماد الخطة الذكية",
  "Realtime operations": "العمليات المباشرة",
  "Socket.IO waiting for driver, task, guest, and delay events":
    "بانتظار أحداث السائق والمهام والضيوف والتنبيهات",
  Loading: "جاري تحميل",
  "Live driver map": "خريطة السائقين المباشرة",
  "Built-in Riyadh map": "خريطة الرياض المدمجة",
  "OpenStreetMap active": "خريطة OpenStreetMap مفعلة",
  "Google Maps API": "خرائط جوجل",
  "Socket.IO live layer": "طبقة التحديث المباشر",
  "Driver location updates": "تحديثات مواقع السائقين",
  "Task status changes": "تغييرات حالة المهام",
  "Guest arrivals": "وصول الضيوف",
  "Delay alerts": "تنبيهات التأخير",

  "Riyadh Season International Guests Program":
    "برنامج ضيوف موسم الرياض الدوليين",
  Riyadh: "الرياض",
  "Riyadh Future Hospitality Summit": "قمة الرياض لمستقبل الضيافة",
  "VIP investor reception and conference requiring airport transfers, premium hotel rooms, catering, and cultural tours.":
    "استقبال ومؤتمر للمستثمرين من فئة VIP يتطلب نقل المطار وغرف فندقية فاخرة وضيافة وجولات ثقافية.",
  "King Abdullah Financial District": "مركز الملك عبدالله المالي",
  "Mandarin Oriental Al Faisaliah": "ماندارين أورينتال الفيصلية",
  "Boulevard City, Riyadh": "بوليفارد سيتي، الرياض",
  "Boulevard City": "بوليفارد سيتي",
  "King Khalid International Airport - Gate A4":
    "مطار الملك خالد الدولي - البوابة A4",
  "King Khalid International Airport": "مطار الملك خالد الدولي",
  "Four Seasons Riyadh": "فورسيزونز الرياض",
  "Voco Riyadh": "فوكو الرياض",
  Diriyah: "الدرعية",
  "Boulevard City to Diriyah, then hotel":
    "من بوليفارد سيتي إلى الدرعية ثم الفندق",
  "Voco Riyadh to Boulevard City": "من فوكو الرياض إلى بوليفارد سيتي",
  "Private dinner transfer after the venue": "نقل خاص للعشاء بعد الفعالية",
  "Guest photo shared with captain.": "تمت مشاركة صورة الضيف مع الكابتن.",
  "Notify guest 3 minutes before car arrives.":
    "تنبيه الضيف قبل وصول السيارة بثلاث دقائق.",
  "Personal dinner trip after event": "رحلة عشاء خاصة بعد الفعالية",
  "Add one passenger to shuttle group": "إضافة راكب إلى مجموعة النقل",
  "Central Shuttle Supervisor": "مشرف النقل المركزي",
  "Riyadh Season logistics daily report":
    "تقرير لوجستيات موسم الرياض اليومي",
  "Arrival completion": "اكتمال الوصول",
  "VIP cars ready": "سيارات VIP جاهزة",
  "Shuttle grouping": "تجميع النقل الجماعي",
  "Open guest requests": "طلبات الضيوف المفتوحة",
  "Welcome to Riyadh hospitality": "مرحباً بكم في ضيافة الرياض",
  "Riyadh Season experience preview": "لمحة عن تجربة موسم الرياض",
  "Black GMC Yukon - RUH 8841": "جي إم سي يوكن أسود - RUH 8841",
  "Organizing Company Ops": "عمليات الشركة المنظمة",
  "Platform leadership": "قيادة المنصة",
  "Founder & CEO": "المؤسس والرئيس التنفيذي",
  "Developer & Quantitative Specialist": "المطور والمتخصص الكمي",
  "Rashed Mohamed": "راشد محمد",
  "Mohamed Izeldin": "محمد عزالدين",
  "Midyaf Admin": "محمد عزالدين",
  "Rakan Transport Coordinator": "راكان منسق النقل",
  "Noura Al Harbi": "نورة الحربي",
  "Omar Khan": "عمر خان",
  "Fahad Al Qahtani": "فهد القحطاني",
  "Riyadh Elite Hospitality": "ضيافة الرياض الفاخرة",
  "Najd Palace Suites": "أجنحة قصر نجد",
  "Diriyah Executive Cars": "سيارات الدرعية التنفيذية",
  "Riyadh Ticketing Agency": "وكالة تذاكر الرياض",
  "Saffron Majlis Catering": "ضيافة مجلس الزعفران",
  "Executive suite night": "ليلة جناح تنفيذي",
  "VIP SUV transfer": "نقل VIP بسيارة SUV",
  "Luxury Saudi coffee service": "خدمة قهوة سعودية فاخرة",
  "Premium room with Arabic welcome amenities.":
    "غرفة فاخرة مع مستلزمات ترحيب عربية.",
  "Bilingual chauffeur and bottled water.":
    "سائق يتحدث لغتين مع مياه معبأة.",
  "Dates, Saudi coffee, and premium display equipment.":
    "تمور وقهوة سعودية ومعدات عرض فاخرة.",
  "Normal group 4": "المجموعة العادية ٤",
  "Logistics Manager": "مدير اللوجستيات",
  "5-star and 4-star room allocation": "تخصيص غرف ٥ نجوم و٤ نجوم",
  "VIP SUVs, luxury sedans, and shuttle vehicles":
    "سيارات SUV للـ VIP وسيدان فاخرة ومركبات نقل جماعي",
  "18 first class + 78 normal tickets":
    "١٨ تذكرة درجة أولى + ٧٨ تذكرة عادية",
  "VIP full-stay car": "سيارة VIP طوال الإقامة",
  "5-star hotel room": "غرفة فندق ٥ نجوم",
  "SUV GMC/Tahoe with captain": "سيارة GMC/Tahoe مع كابتن",
  "Grouped shuttle transfer": "نقل جماعي",
  "First class event ticket": "تذكرة فعالية درجة أولى",
  "Normal event ticket": "تذكرة فعالية عادية",
  "VIP guests receive dedicated sedan/SUV coverage for the full Riyadh stay. Normal guests are grouped into 3-4 person shuttle movements for airport-hotel, hotel-venue, venue-hotel, and hotel-airport.":
    "يحصل ضيوف VIP على سيارة سيدان أو SUV مخصصة طوال فترة الإقامة في الرياض. ويتم تجميع الضيوف العاديين في نقل جماعي من ٣ إلى ٤ أشخاص لمسارات المطار والفندق وموقع الفعالية والمغادرة.",
  "VIP guests receive dedicated cars for the full Riyadh stay. Normal guests are grouped into 3-4 person shuttle movements.":
    "يحصل ضيوف VIP على سيارات مخصصة طوال فترة الإقامة في الرياض، ويتم تجميع الضيوف العاديين في رحلات نقل جماعي من ٣ إلى ٤ أشخاص.",
  "18 VIP guests require full-stay vehicle allocation.":
    "١٨ ضيف VIP يحتاجون إلى سيارات مخصصة طوال فترة الإقامة.",
  "78 normal guests grouped into 20 shuttle groups.":
    "٧٨ ضيفاً عادياً يتم تجميعهم في ٢٠ مجموعة نقل جماعي.",
  "78 normal guests grouped into shuttle movements.":
    "٧٨ ضيفاً عادياً يتم تجميعهم في رحلات نقل جماعي.",
  "First class tickets are reserved for VIP guests.":
    "تذاكر الدرجة الأولى مخصصة لضيوف VIP.",
  "Five-star rooms are reserved for VIPs; four-star rooms for normal guests.":
    "غرف الخمس نجوم مخصصة لضيوف VIP، وغرف الأربع نجوم للضيوف العاديين.",
  "Vendor quotation collection": "جمع عروض الموردين",
  "Contract confirmation": "اعتماد العقود",
  "Arrival operations": "عمليات الوصول",
  "Departure operations": "عمليات المغادرة",
  "In progress": "قيد التنفيذ",
  "72%": "٧٢٪",
  "18/18": "١٨/١٨",
  "20 groups": "٢٠ مجموعة",
  "2": "٢",
  HOTEL_OPERATOR: "مشغل الفنادق",
  CAR_RENTAL: "تأجير السيارات",
  TICKET_AGENCY: "وكالة التذاكر",
  HOTEL: "فندق",
  CAR: "سيارات",
  TICKET: "تذاكر",
  CATERING: "ضيافة",
  EQUIPMENT: "معدات",
  TOURISM: "سياحة",
  AIRPORT_PICKUP: "استقبال من المطار",
  HOTEL_TRANSFER: "نقل الفندق",
  VENUE_TRANSFER: "نقل موقع الفعالية",
  RESTAURANT_PICKUP: "نقل مطعم",
  VIP_ESCORT: "مرافقة VIP",
  NORTH_RIYADH: "شمال الرياض",
  CENTRAL_RIYADH: "وسط الرياض",
  EAST_RIYADH: "شرق الرياض",
  WEST_RIYADH: "غرب الرياض",
  SOUTH_RIYADH: "جنوب الرياض",
  DIRIYAH_CORRIDOR: "ممر الدرعية",

  VIP: "VIP",
  SHUTTLE: "نقل جماعي",
  MIXED: "مختلط",
  FIRST_CLASS: "درجة أولى",
  NORMAL: "عادي",
  GUEST: "ضيف",
  DRIVER: "سائق",
  ORGANIZER: "منظم",
  SUPPLIER: "مورد",
  SUPER_ADMIN: "مشرف عام",
  COORDINATOR: "منسق",
  LOGISTICS_MANAGER: "مدير اللوجستيات",
  COMPANY_ORGANIZER: "الشركة المنظمة",
  ARRIVAL: "الوصول",
  DEPARTURE: "المغادرة",
  INVITED: "مدعو",
  DECLINED: "معتذر",
  PUBLISHED: "منشور",
  OFFLINE: "غير متصل",
  AVAILABLE: "متاح",
  BUSY: "مشغول",
  FIVE_STAR: "٥ نجوم",
  FOUR_STAR: "٤ نجوم",
  LUXURY_SEDAN: "سيدان فاخرة",
  SUV_GMC_TAHOE: "GMC أو Tahoe",
  OPERATIONS_OPEN: "العمليات مفتوحة",
  AI_PLANNING: "قيد التخطيط الذكي",
  PLAN_CONFIRMED: "الخطة معتمدة",
  QUOTING: "قيد طلب العروض",
  CONTRACTING: "قيد التعاقد",
  DRAFT: "مسودة",
  LIVE: "مباشر",
  PENDING: "قيد الانتظار",
  CONFIRMED: "مؤكد",
  IN_PROGRESS: "قيد التنفيذ",
  ASSIGNED: "تم التعيين",
  ACCEPTED: "تم القبول",
  EN_ROUTE: "في الطريق",
  ARRIVED: "وصل",
  PICKED_UP: "تم الاستلام",
  COMPLETED: "مكتملة",
  DELAYED: "متأخرة",
  CANCELLED: "ملغاة",
  PRE_ARRIVAL: "قبل الوصول",
  PASSPORT: "الجوازات",
  LUGGAGE: "الأمتعة",
  GATE: "البوابة",
  VISA: "تأشيرة",
  GUEST_PHOTO: "صورة الضيف",
  DRIVER_PHOTO: "صورة الكابتن",
  PROMO_VIDEO: "فيديو تعريفي",
  REPORT_PDF: "تقرير PDF",
  OTHER: "ملف آخر",
  READY: "جاهز",
  SENT: "تم الإرسال",
  ACKNOWLEDGED: "تم الاستلام",
  RECEIVED: "تم الاستلام",
  WAITING: "بانتظار",
  WHATSAPP: "واتساب",
  SMS: "رسائل نصية",
  FCM: "تنبيه التطبيق",
  IN_APP: "داخل التطبيق",
  queued: "مجدول للإرسال",
  "sms-provider-pending": "مزود الرسائل قيد الربط",
  "whatsapp-provider-pending": "مزود واتساب قيد الربط",
  "firebase-fcm-pending": "Firebase FCM قيد الربط",
  "midyaf-in-app": "إشعارات مضياف الداخلية",
  "Visa sent to guest app": "تم إرسال التأشيرة إلى تطبيق الضيف",
  "Ticket sent to guest app": "تم إرسال التذكرة إلى تطبيق الضيف",
  "Hospitality video sent": "تم إرسال فيديو الضيافة",
  "Midyaf update sent": "تم إرسال تحديث من مضياف",
  "Your visa document is now available in Midyaf.":
    "مستند التأشيرة متاح الآن في مضياف.",
  "Your event ticket is now available in Midyaf.":
    "تذكرة الفعالية متاحة الآن في مضياف.",
  "A Riyadh hospitality video has been added to your guest app.":
    "تمت إضافة فيديو ضيافة الرياض إلى تطبيق الضيف.",
  "A new Midyaf update is available.": "يتوفر تحديث جديد في مضياف.",
  "Guest photo sent to captain": "تم إرسال صورة الضيف إلى الكابتن",
  "Captain details updated": "تم تحديث بيانات الكابتن",
  "Guest photo is ready for pickup handoff.":
    "صورة الضيف جاهزة لتسليم الاستقبال.",
  "Captain photo and details are ready in the guest app.":
    "صورة الكابتن وبياناته جاهزة في تطبيق الضيف.",
  VIP_CAPTAIN: "كابتن VIP",
  EMERGENCY: "طوارئ",
  REQUESTED: "مطلوب",
  RECOMMENDED: "موصى به",
  APPROVED: "معتمد",
  REJECTED: "مرفوض",
  SIGNED: "موقع",
  ACTIVE: "نشط",
  MANAGER_CONFIRMED: "معتمد من المدير",
  SENT_TO_COMPANY: "مرسل للشركة",
  NEW: "جديد",
  SENT_TO_SUPERVISOR: "مرسل للمشرف",
  CLOSED: "مغلق",
  night: "ليلة",
  day: "يوم",
  guest: "ضيف",
  ticket: "تذكرة",
  "18 VIP dedicated vehicles; 78 normal guests in 20 groups.":
    "١٨ سيارة مخصصة لكبار الشخصيات و٧٨ ضيفاً عادياً في ٢٠ مجموعة.",
  "Entertainment activity logistics for VIP and normal guests: visas, tickets, hotels, arrivals, hotel-venue movement, and departures.":
    "لوجستيات فعالية ترفيهية لكبار الشخصيات والضيوف العاديين: التأشيرات والتذاكر والفنادق والوصول والتنقل بين الفندق والموقع والمغادرة.",
  "Five-star Riyadh hotel room with VIP welcome amenities.":
    "غرفة فندقية خمس نجوم في الرياض مع مستلزمات ترحيب لكبار الشخصيات.",
  "Dedicated SUV for VIP guest full Riyadh stay.":
    "سيارة SUV مخصصة لضيف VIP طوال الإقامة في الرياض.",
  "Airport-hotel and hotel-venue grouped movements.":
    "تنقلات جماعية بين المطار والفندق وبين الفندق وموقع الفعالية.",
  "Premium entrance and hospitality access.":
    "دخول مميز وتجربة ضيافة خاصة.",
  "Standard event access.": "دخول عادي للفعالية.",
  "Passport control delays could bunch VIP arrivals.":
    "قد تؤدي تأخيرات الجوازات إلى تكدس وصول ضيوف VIP.",
  "Normal guest grouping must be updated if flights change.":
    "يجب تحديث مجموعات الضيوف العاديين عند تغير الرحلات.",
  "Boulevard City evening traffic requires early hotel departure windows.":
    "ازدحام بوليفارد سيتي المسائي يتطلب نوافذ مغادرة مبكرة من الفندق.",
  "Boulevard City evening traffic requires early departure windows.":
    "ازدحام بوليفارد سيتي المسائي يتطلب نوافذ مغادرة مبكرة.",
  "Guest received at gate A4. VIP sedan was clean and ready.":
    "تم استقبال الضيف عند البوابة A4، وكانت سيارة VIP السيدان نظيفة وجاهزة.",
  "Guest received at gate A4. VIP vehicle ready.":
    "تم استقبال الضيف عند البوابة A4، وسيارة VIP جاهزة.",
  "18 VIP dedicated vehicles; 78 normal guests in groups.":
    "١٨ سيارة مخصصة لكبار الشخصيات و٧٨ ضيفاً عادياً ضمن مجموعات.",
  platinum: "بلاتيني"
};

export function localizeText(value: string | number | null | undefined, isArabic: boolean) {
  if (value === null || value === undefined) {
    return "";
  }

  const text = String(value);

  if (!isArabic) {
    return text.replaceAll("_", " ");
  }

  return translations[text] ?? text.replaceAll("_", " ");
}

export function localizeStatus(value: string, isArabic: boolean) {
  return localizeText(value, isArabic);
}

export function localizeList(items: string[], isArabic: boolean) {
  return items.map((item) => localizeText(item, isArabic));
}
